// packages/backend/server-go/controllers/workspace_controller.go
package controllers

import (
	"encoding/json"
	"fmt"
	"time"

	"app/server-go/models"
	"github.com/beego/beego/v2/client/orm"
	beego "github.com/beego/beego/v2/server/web"
	// "github.com/google/uuid" // Not needed as DB handles UUID generation for ID
)

type WorkspaceController struct {
	beego.Controller
}

type CreateWorkspacePayload struct {
	Name               *string `json:"name,omitempty"`
	Public             bool    `json:"public"`
	EnableAI           *bool   `json:"enableAi,omitempty"`
	EnableURLPreview   *bool   `json:"enableUrlPreview,omitempty"`
	EnableDocEmbedding *bool   `json:"enableDocEmbedding,omitempty"`
}

// @Title CreateWorkspace
// @Description Create a new workspace
// @Param	body	body 	CreateWorkspacePayload	true	"Payload for creating a workspace"
// @Success 201 {object} models.Workspace "Workspace created successfully"
// @Failure 400 {object} map[string]string "Invalid input"
// @Failure 500 {object} map[string]string "Failed to create workspace"
// @router / [post]
func (c *WorkspaceController) CreateWorkspace() {
	var payload CreateWorkspacePayload
	if err := json.Unmarshal(c.Ctx.Input.RequestBody, &payload); err != nil {
		c.Ctx.Output.SetStatus(400)
		c.Data["json"] = map[string]string{"error": "Invalid request payload: " + err.Error()}
		c.ServeJSON()
		return
	}

	o := orm.NewOrm()
	ws := models.Workspace{
		// ID is generated by gen_random_uuid() in the database by default
		Public:    payload.Public,
		CreatedAt: time.Now(), // auto_now_add in ORM tag should handle this
	}

	if payload.Name != nil {
		ws.Name = payload.Name
	} else {
		defaultName := "Untitled Workspace" // Or return validation error if name is required
		ws.Name = &defaultName
	}

	// Set optional boolean fields, respecting defaults from model/db if payload field is nil
	// Model defaults: EnableAI=true, EnableURLPreview=false, EnableDocEmbedding=true
	ws.EnableAI = true
	if payload.EnableAI != nil {
		ws.EnableAI = *payload.EnableAI
	}
	ws.EnableURLPreview = false
	if payload.EnableURLPreview != nil {
		ws.EnableURLPreview = *payload.EnableURLPreview
	}
	ws.EnableDocEmbedding = true
	if payload.EnableDocEmbedding != nil {
		ws.EnableDocEmbedding = *payload.EnableDocEmbedding
	}
	// ws.Indexed defaults to false (Go default for bool), which matches model default.

	// The `SID` field is auto-incrementing and will be handled by the DB/ORM.
	// The `ID` field (VARCHAR UUID) is handled by the DB's `gen_random_uuid()` default.
	insertedId, err := o.Insert(&ws) // InsertedId here will be the value of the auto-incrementing PK if one was defined (e.g. SID if it were the ORM PK)
	                                 // Since our PK is 'ID' (string UUID), Insert returns the number of rows on success for some DBs or specific PK value if supported.
	                                 // For string PKs not auto-generated by app, we need to Read it back to get SID and confirm ID.
	if err != nil {
		c.Ctx.Output.SetStatus(500)
		c.Data["json"] = map[string]string{"error": "Failed to create workspace: " + err.Error()}
		c.ServeJSON()
		return
	}

    // If ws.ID (UUID) is set by DB default, we need to retrieve the created object
    // to get its actual ID and SID. However, o.Insert(&ws) might populate ws.ID if the driver supports it.
    // For Beego ORM with string PKs and DB defaults, it's safer to re-read or ensure the driver populates it.
    // Let's assume for now the driver might populate ws.ID (UUID) if it's returned by DB.
    // If not, we would need to do: o.Read(&ws, "Id") after knowing the ID, or query by another unique field if ID is not known.
    // Since ID is the PK, and it's a string, Insert() might not update it directly in the struct for all drivers.
    // However, `SID` is auto, so that would be populated if it were the PK.
    // Let's return the `ws` struct as is; the client might not immediately need the DB-generated ID if it's a new resource.
    // A better approach for string UUID PKs set by DB is to query it back if needed immediately.
    // For now, we'll assume the client can discover the ID later or `Insert` populates it.
    // If `insertedId` from `o.Insert()` is the `SID` (if `SID` was primary key):
    // ws.SID = int(insertedId) // This would be relevant if SID was the PK.

    // Since ID is the PK and is a string (UUID from DB), we should retrieve the full workspace record
    // to ensure all fields (especially ID and SID) are correctly populated.
    // This is a common pattern when DB generates some PK fields.
    // However, to keep it simple as per initial request, we'll return the current `ws` object.
    // The client will receive the payload values, plus CreatedAt. The actual ID and SID might be missing or zero.
    // THIS IS A SIMPLIFICATION. A robust implementation would re-fetch.
    // Let's try to fetch it by a known value if possible, or assume Insert populates it.
    // If Insert does not populate the string ID, this response will be incomplete.
    // Given the model `ID string orm:"pk;type(varchar);column(id)"` and DB default,
    // Beego's ORM with lib/pq *should* populate ws.ID after insert if RETURNING id is used by ORM.

	c.Ctx.Output.SetStatus(201)
	c.Data["json"] = ws // ws should contain the ID if ORM/driver supports RETURNING for string PKs
	c.ServeJSON()
}

// @Title GetWorkspaceByID
// @Description Get a workspace by its UUID
// @Param	workspaceId		path 	string	true		"The UUID of the workspace"
// @Success 200 {object} models.Workspace
// @Failure 400 {object} map[string]string "Workspace ID is required"
// @Failure 404 {object} map[string]string "Workspace not found"
// @Failure 500 {object} map[string]string "Failed to retrieve workspace"
// @router /:workspaceId [get]
func (c *WorkspaceController) GetWorkspaceByID() {
	workspaceID := c.Ctx.Input.Param(":workspaceId")
	if workspaceID == "" {
		c.Ctx.Output.SetStatus(400)
		c.Data["json"] = map[string]string{"error": "Workspace ID is required"}
		c.ServeJSON()
		return
	}

	o := orm.NewOrm()
	ws := models.Workspace{ID: workspaceID}
	err := o.Read(&ws) // Read using the PK field 'ID'

	if err == orm.ErrNoRows {
		c.Ctx.Output.SetStatus(404)
		c.Data["json"] = map[string]string{"error": "Workspace not found"}
	} else if err != nil {
		c.Ctx.Output.SetStatus(500)
		c.Data["json"] = map[string]string{"error": "Failed to retrieve workspace: " + err.Error()}
	} else {
		c.Data["json"] = ws
	}
	c.ServeJSON()
}

// @Title GetAllWorkspaces
// @Description Get a list of all workspaces
// @Success 200 {array} models.Workspace
// @Failure 500 {object} map[string]string "Failed to retrieve workspaces"
// @router / [get]
func (c *WorkspaceController) GetAllWorkspaces() {
	o := orm.NewOrm()
	var workspaces []*models.Workspace
	_, err := o.QueryTable(new(models.Workspace)).All(&workspaces)

	if err != nil {
		c.Ctx.Output.SetStatus(500)
		c.Data["json"] = map[string]string{"error": "Failed to retrieve workspaces: " + err.Error()}
	} else {
		if workspaces == nil { // Ensure we return an empty array instead of null
			workspaces = []*models.Workspace{}
		}
		c.Data["json"] = workspaces
	}
	c.ServeJSON()
}

type UpdateWorkspacePayload struct {
	Name               *string `json:"name,omitempty"`
	Public             *bool   `json:"public,omitempty"`
	EnableAI           *bool   `json:"enableAi,omitempty"`
	EnableURLPreview   *bool   `json:"enableUrlPreview,omitempty"`
	EnableDocEmbedding *bool   `json:"enableDocEmbedding,omitempty"`
}

// @Title UpdateWorkspace
// @Description Update an existing workspace
// @Param	workspaceId		path 	string	true		"The UUID of the workspace to update"
// @Param	body		body 	UpdateWorkspacePayload	true		"Payload for updating a workspace"
// @Success 200 {object} models.Workspace "Workspace updated successfully"
// @Failure 400 {object} map[string]string "Invalid input or ID"
// @Failure 404 {object} map[string]string "Workspace not found"
// @Failure 500 {object} map[string]string "Failed to update workspace"
// @router /:workspaceId [put]
func (c *WorkspaceController) UpdateWorkspace() {
	workspaceID := c.Ctx.Input.Param(":workspaceId")
	if workspaceID == "" {
		c.Ctx.Output.SetStatus(400)
		c.Data["json"] = map[string]string{"error": "Workspace ID is required"}
		c.ServeJSON()
		return
	}

	var payload UpdateWorkspacePayload
	if err := json.Unmarshal(c.Ctx.Input.RequestBody, &payload); err != nil {
		c.Ctx.Output.SetStatus(400)
		c.Data["json"] = map[string]string{"error": "Invalid request payload: " + err.Error()}
		c.ServeJSON()
		return
	}

	o := orm.NewOrm()
	ws := models.Workspace{ID: workspaceID}

	if err := o.Read(&ws); err != nil {
		if err == orm.ErrNoRows {
			c.Ctx.Output.SetStatus(404)
			c.Data["json"] = map[string]string{"error": "Workspace not found"}
		} else {
			c.Ctx.Output.SetStatus(500)
			c.Data["json"] = map[string]string{"error": "Failed to retrieve workspace for update: " + err.Error()}
		}
		c.ServeJSON()
		return
	}

	// Update fields if provided in payload
	fieldsToUpdate := []string{}
	if payload.Name != nil {
		ws.Name = payload.Name
		fieldsToUpdate = append(fieldsToUpdate, "Name")
	}
	if payload.Public != nil {
		ws.Public = *payload.Public
		fieldsToUpdate = append(fieldsToUpdate, "Public")
	}
	if payload.EnableAI != nil {
		ws.EnableAI = *payload.EnableAI
		fieldsToUpdate = append(fieldsToUpdate, "EnableAI")
	}
	if payload.EnableURLPreview != nil {
		ws.EnableURLPreview = *payload.EnableURLPreview
		fieldsToUpdate = append(fieldsToUpdate, "EnableURLPreview")
	}
	if payload.EnableDocEmbedding != nil {
		ws.EnableDocEmbedding = *payload.EnableDocEmbedding
		fieldsToUpdate = append(fieldsToUpdate, "EnableDocEmbedding")
	}

    // Add UpdatedAt logic if model has it (Workspace model doesn't have UpdatedAt)
    // ws.UpdatedAt = time.Now()
    // fieldsToUpdate = append(fieldsToUpdate, "UpdatedAt")


	if len(fieldsToUpdate) > 0 {
		if _, err := o.Update(&ws, fieldsToUpdate...); err != nil {
			c.Ctx.Output.SetStatus(500)
			c.Data["json"] = map[string]string{"error": "Failed to update workspace: " + err.Error()}
			c.ServeJSON()
			return
		}
	} else {
        // No fields to update, return current workspace or a message
        c.Data["json"] = map[string]interface{}{"message": "No fields to update", "workspace": ws}
        c.ServeJSON()
        return
    }

	c.Data["json"] = ws
	c.ServeJSON()
}

// @Title DeleteWorkspace
// @Description Delete a workspace by its UUID
// @Param	workspaceId		path 	string	true		"The UUID of the workspace to delete"
// @Success 200 {object} map[string]string "Workspace deleted successfully"
// @Failure 400 {object} map[string]string "Workspace ID is required"
// @Failure 404 {object} map[string]string "Workspace not found"
// @Failure 500 {object} map[string]string "Failed to delete workspace"
// @router /:workspaceId [delete]
func (c *WorkspaceController) DeleteWorkspace() {
	workspaceID := c.Ctx.Input.Param(":workspaceId")
	if workspaceID == "" {
		c.Ctx.Output.SetStatus(400)
		c.Data["json"] = map[string]string{"error": "Workspace ID is required"}
		c.ServeJSON()
		return
	}

	o := orm.NewOrm()
	// Check if workspace exists by attempting to read it first.
	// This is important because Delete returns number of rows affected, which could be 0 if not found.
	ws := models.Workspace{ID: workspaceID}
	if errRead := o.Read(&ws); errRead != nil {
		if errRead == orm.ErrNoRows {
			c.Ctx.Output.SetStatus(404)
			c.Data["json"] = map[string]string{"error": "Workspace not found"}
		} else {
			c.Ctx.Output.SetStatus(500)
			c.Data["json"] = map[string]string{"error": "Error checking workspace before delete: " + errRead.Error()}
		}
		c.ServeJSON()
		return
	}

	// If Read was successful, then proceed to delete.
	if num, err := o.Delete(&models.Workspace{ID: workspaceID}); err != nil {
		c.Ctx.Output.SetStatus(500)
		c.Data["json"] = map[string]string{"error": "Failed to delete workspace: " + err.Error()}
	} else if num == 0 {
		// This case should ideally be caught by the Read above.
		c.Ctx.Output.SetStatus(404)
		c.Data["json"] = map[string]string{"error": "Workspace not found (no rows deleted)"}
	} else {
		c.Data["json"] = map[string]string{"message": fmt.Sprintf("Workspace %s deleted successfully", workspaceID)}
	}
	c.ServeJSON()
}
